version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: ${DB_NAME}
    restart: always
    
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
